# Generated by Django 2.0 on 2020-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UTI_NOM', models.CharField(max_length=50)),
                ('UTI_PRENOM', models.CharField(max_length=50)),
                ('UTI_CIVILITE', models.CharField(max_length=1)),
                ('UTI_EMAIL', models.CharField(max_length=50)),
                ('UTI_ADRESSE', models.CharField(max_length=300)),
                ('UTI_SUPPRIME', models.BooleanField()),
            ],
        ),
    ]
