# Generated by Django 2.0 on 2020-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sie_Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UTI_NOM', models.CharField(max_length=50)),
                ('UTI_PRENOM', models.CharField(max_length=50)),
                ('UTI_CIVILITE', models.CharField(max_length=1)),
                ('UTI_EMAIL', models.CharField(max_length=50)),
                ('UTI_SUPPRIME', models.BooleanField()),
                ('UTI_ADRESSE', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
